package edu.uth;

import java.util.List;

public class Admin extends User {
    private String adminLevel;

    public Admin(String userId, String username, String password, String email, String adminLevel) {
        super(userId, username, password, email, Role.ADMIN);
        this.adminLevel = adminLevel;
    }

    public void manageFacility() {
        manageFacility(Main.getFacilities());
    }

    public void manageFacility(List<Facility> facilities) {
        System.out.println("Admin " + getUsername() + " is managing facilities.");
        if (facilities.isEmpty()) {
            System.out.println("  No facilities registered.");
        } else {
            for (Facility f : facilities) {
                System.out.println("---------------------------");
                System.out.println(f);
                System.out.println("---------------------------");
            }
        }
    }

    public void manageTrainer() {
        manageTrainer(Main.getTrainers());
    }

    public void manageTrainer(List<Trainer> trainers) {
        System.out.println("Admin " + getUsername() + " is managing trainers.");
        if (trainers.isEmpty()) {
            System.out.println("  No trainers registered.");
        } else {
            for (Trainer t : trainers) {
                System.out.println("---------------------------");
                System.out.println(t);
                System.out.println("---------------------------");
            }
        }
    }

    public void updateMemberProfile() {
        System.out.println("Admin " + getUsername() + " is updating member profiles.");
    }

    public void updateMemberProfile(Member member, String email) {
        if (member != null) {
            member.setEmail(email);
            System.out.println("Admin " + getUsername() + " updated member " + member.getUsername() + " email to " + email);
        }
    }

    public void addMember() {
        System.out.println("Admin " + getUsername() + " is adding a new member.");
    }

    public void addMember(Member member, List<Member> members) {
        if (member != null && !members.contains(member)) {
            members.add(member);
            System.out.println("Admin " + getUsername() + " added member: " + member.getUsername());
        }
    }

    public void updateMember() {
        System.out.println("Admin " + getUsername() + " is updating member information.");
    }

    public void updateMember(Member member, String email) {
        updateMemberProfile(member, email);
    }

    public void deleteMember() {
        System.out.println("Admin " + getUsername() + " is deleting a member.");
    }

    public void deleteMember(Member member, List<Member> members) {
        if (member != null && members.contains(member)) {
            members.remove(member);
            System.out.println("Admin " + getUsername() + " deleted member: " + member.getUsername());
        }
    }

    public void managePlan() {
        managePlan(Main.getPlans());
    }

    public void managePlan(List<SubscriptionPlan> plans) {
        System.out.println("Admin " + getUsername() + " is managing subscription plans.");
        if (plans.isEmpty()) {
            System.out.println("  No subscription plans available.");
        } else {
            for (SubscriptionPlan p : plans) {
                System.out.println("---------------------------");
                System.out.println(p);
                System.out.println("---------------------------");
            }
        }
    }

    public void generateRevenue() {
        generateRevenueReport(Main.getSubscriptions());
    }

    public void generateRevenueReport(List<Subscription> subscriptions) {
        System.out.println("\n========== REVENUE REPORT ==========");
        System.out.println("Generated by Admin: " + getUsername());
        double totalRevenue = 0;
        long activeCount = 0;
        long expiredCount = 0;

        for (Subscription sub : subscriptions) {
            boolean isExpired = sub.getEndDate() != null && sub.getEndDate().isBefore(java.time.LocalDate.now());
            if ("active".equalsIgnoreCase(sub.getStatus()) && !isExpired) {
                totalRevenue += sub.getAmountPaid();
                activeCount++;
            } else {
                expiredCount++;
            }
        }
        System.out.println("Total Revenue: $" + String.format("%.2f", totalRevenue));
        System.out.println("Active Subscriptions: " + activeCount);
        System.out.println("Expired/Inactive Subscriptions: " + expiredCount);
        System.out.println("====================================\n");
    }

    public void generateAttendance() {
        generateAttendanceReport(Main.getAttendances());
    }

    public void generateAttendanceReport(List<Attendance> attendances) {
        System.out.println("\n========== ATTENDANCE REPORT ==========");
        System.out.println("Generated by Admin: " + getUsername());
        long totalPresent = attendances.stream()
                .filter(a -> "present".equalsIgnoreCase(a.getStatus())).count();
        System.out.println("Total Present Records: " + totalPresent);
        System.out.println("Total Attendance Records: " + attendances.size());
        System.out.println("Overall Attendance Rate: " + 
                (attendances.isEmpty() ? "0.00%" : String.format("%.2f%%", 
                (totalPresent * 100.0 / attendances.size()))));
        System.out.println("========================================\n");
    }

    public String getAdminLevel() {
        return adminLevel;
    }

    public void setAdminLevel(String adminLevel) {
        this.adminLevel = adminLevel;
    }

    @Override
    public String toString() {
        return super.toString() + "\n" +
               "adminLevel: " + adminLevel;
    }
}
